# Menus
menu:
    # Home: /hexo-theme-hueman/
    Home: /
    Ricettario: /groups.html
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About: /about.html

# Customize
customize:
    logo:
        width: 320
        height: 121
        # url: images/logo-header.png
        # url: images/logo.jpg
        url: images/logo_web.png
    theme_color: '#FF9F4C'
    highlight: androidstudio
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        # twitter: /
        # facebook: /
        # google-plus: /
        github: https://github.com/erirai
        instagram: http://instagram.com/erica_raiano
        # weibo: /
        # rss: /

# Widgets
widgets:
    - recent_posts
    # - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false
    local: true

# Comment
comment:
    disqus: frangipani # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    scrollLoading: true # options: true, false
    google_analytics: UA-42950201-2 # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        BAKERIA: http://bakeria.ch/
        Belles Fleurs: http://bellesfleurs.ch/
