# Menus
menu:
    # Home: /hexo-theme-hueman/
    Home:
      default: /
      it: /it
      de: /de
    Ricettario:
      default: /groups.html
      it: /groups.html
      de: /groups-de.html
    # Delete this row if you don't want categories in your header nav bar
    Categories:
    About:
      default: /about.html
      it: /about.html
      de: /about-de.html

# Customize
customize:
    logo:
        width: 320
        height: 121
        # url: images/logo-header.png
        # url: images/logo.jpg
        url: images/logo_web.png
    theme_color: '#FF9F4C'
    highlight: androidstudio
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    social_links: # for more icons, please see http://fontawesome.io/icons/#brand
        # google-plus: /
        instagram: http://instagram.com/erica_raiano
        pinterest: https://www.pinterest.com/ericaraiano
        youtube: https://www.youtube.com/channel/UCdBfmHzuTKjZDC7GyFEuTXA
        x-twitter: https://x.com/erica_raiano
        github: https://github.com/erirai
        # steemit: https://steemit.com/@frangipani
        facebook: https://www.facebook.com/ProfumoDiFrangipani
        mail: mailto:profumodifrangipani@outlook.com
        # weibo: /
        # rss: /

# Widgets
widgets:
    - recent_posts
    # - category
    - archive
    # - tag
    - tagcloud
    - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false
    local: false

# Comment
comment:
    disqus: #frangipani # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    #fancybox: true # options: true, false
    #scrollLoading: true # options: true, false
    lightgallery: true # options: true, false
    google_analytics: G-G5EQ1LNSEF # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id: erica_raiano
        google_plus:
    links:
        Marlene's Sweet Things: https://marlenessweetthings.ch
        Dolcisseria: https://www.dolcisseria.ch
        delizie d'Amelia: https://deliziedamelia.ch 
        Vale's Food Blog: https://www.valesfoodblog.ch 
        Steffi's Chuchichistli: https://steffis-chuchichistli.ch
        atelier nefwiss: https://nefwiss.ch 
        Foodblogs Schweiz: https://www.foodblogs-schweiz.ch 
        Oreegano: https://www.oreegano.com/profile/profumodifrangipani/recipebook
