index:
    home: 'Home'
    about: 'Su di me'
    ricettario: 'Ricettario'
    search: 'Cerca'
    archive: 'Archivio'
    category: 'Categoria'
    uncategorized: 'Non categorizzato'
    tag: 'Tag'
nav:
    current_page:
        other: 'Pagina %d '
    total_page:
        other: 'di %d'
sidebar:
    follow: 'segui'
    newer: 'più recente'
    older: 'precedente'
    recents: 'Recenti'
    archives: 'Archiviati'
    categories: 'Categorie'
    links: 'link'
    tags: 'tag'
    tag_cloud: 'tag cloud'
article:
    comments: 'Commenti'
    share: 'Condividi'
insight:
    hint: 'inserisci qualcosa...'
    posts: 'Post'
    pages: 'Pagine'
    categories: 'Categorie'
    tags: 'Tag'
    untitled: '(senza titolo)'
categories:
  Dolce: 'Dolce'
  Bevande: 'Bevande'
  Biscotti: 'Biscotti'
  Colazione: 'Colazione'
  Conserve: 'Conserve'
  'Crostate, Tartes...': 'Crostate, Tartes...'
  'Dolci al cucchiaio, Gelati...': 'Dolci al cucchiaio, Gelati...'
  Panificati: 'Panificati'
  'Piccola Pasticceria': 'Piccola Pasticceria'
  Torte: 'Torte'
  Salato: 'Salato'
  Aperitivi: 'Aperitivi'
  'Piatti Unici': 'Piatti Unici'
  'Primi Piatti': 'Primi Piatti'
  'Secondi Piatti e Contorni': 'Secondi Piatti e Contorni'
  'Torte salate, Muffin salati...': 'Torte salate, Muffin salati...'
groups:
  Bevande: 'Bevande'
  Biscotti: 'Biscotti'
  Colazione: 'Colazione'
  Conserve: 'Conserve'
  'Crostate, Tartes...': 'Crostate, Tartes...'
  'Dolci al cucchiaio, Gelati...': 'Dolci al cucchiaio, Gelati...'
  Panificati: 'Panificati'
  'Piccola Pasticceria': 'Piccola Pasticceria'
  Torte: 'Torte'
  Aperitivi: 'Aperitivi'
  'Piatti Unici': 'Piatti Unici'
  'Primi Piatti': 'Primi Piatti'
  'Secondi Piatti e Contorni': 'Secondi Piatti e Contorni'
  'Torte salate, Muffin salati...': 'Torte salate, Muffin salati...'
  "Ricette con la Zucca": 'Ricette con la Zucca' 
